version: '3.4'

services:
  xudonaxbot:
    image: ${DOCKER_REGISTRY-}xudonaxbot
    build:
      context: .
      dockerfile: XudonaxBot.Bot/Dockerfile
    environment:
      - BotOptions__Token=${BOT_TOKEN}
      - BotOptions__TenorApiKey=${TENOR_API_KEY}
